# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SwiftDay03' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  # Pods for SwiftDay03

  target 'SwiftDay03Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDay03UITests' do
    # Pods for testing
  end

end
